name: Feature Request
description: Suggest an idea or improvement
title: "<title>"
labels: [enhancement]
assignees: []

body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues and discussions for similar requests
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: How should this be implemented?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, references, or alternatives considered
